#ifndef RB_RPDB_DATABASE_VERBOSITY_SETTINGS_CONTROLLER
	#define RB_RPDB_DATABASE_VERBOSITY_SETTINGS_CONTROLLER

	#include "rb_RPDB_BaseStandardIncludes.h"
	#include <rpdb/RPDB_Types.h>

void Init_RPDB_DatabaseVerbositySettingsController();

VALUE rb_RPDB_DatabaseVerbositySettingsController_new(	VALUE	klass,
													   VALUE	rb_parent_database_settings_controller );
VALUE rb_RPDB_DatabaseVerbositySettingsController_init(	VALUE	rb_database_verbosity_settings_controller,
	VALUE	rb_parent_database_settings_controller );
	VALUE rb_RPDB_DatabaseVerbositySettingsController_parentEnvironment(	VALUE	rb_database_verbosity_settings_controller );
	VALUE rb_RPDB_DatabaseVerbositySettingsController_parentDatabase(	VALUE	rb_database_verbosity_settings_controller );
	VALUE rb_RPDB_DatabaseVerbositySettingsController_displayAdditionalInformationForDBRegisterFlag( VALUE	rb_database_verbosity_settings_controller );
		VALUE rb_RPDB_DatabaseVerbositySettingsController_turnDisplayAdditionalInformationForDBRegisterFlagOn( VALUE	rb_database_verbosity_settings_controller );
		VALUE rb_RPDB_DatabaseVerbositySettingsController_turnDisplayAdditionalInformationForDBRegisterFlagOff( VALUE	rb_database_verbosity_settings_controller );

#endif
